name: flutter_zoom_sdk
description: Zoom SDK from ZOOM ported to flutter as plugin with all necessary features.
version: 1.1.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  plugin_platform_interface: ^2.1.2
  js: ^0.6.4
  crypto: ^3.0.2
  
  archive: ^3.3.2
  path:

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ahmed.flutter_zoom_sdk
        pluginClass: FlutterZoomSdkPlugin
      ios:
        pluginClass: FlutterZoomSdkPlugin
      web:
        pluginClass: ZoomViewWeb
        fileName: flutter_zoom_web.dart